service: lambda-snapstart-example
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: java11 # Corretto
package:
  artifact: build/libs/lambda-snapstart-0.1-all.jar
functions:
  HelloWorld:
    handler: com.mamezou.FunctionRequestHandler
    url: true
    # snapStart: true
